SimpleTodoApp/Entities/Entity.cs
using Azure;
using Azure.Data.Tables;

namespace SimpleTodoApp.Entities;

public interface IEntity : ITableEntity
{
    int Id { get; }
}

public class Entity : IEntity
{
    public int Id { get; set; }
    public string PartitionKey { get; set; } = string.Empty;
    public string RowKey { get; set; } = string.Empty;
    public DateTimeOffset? Timestamp { get; set; }
    public ETag ETag { get; set; }
}

SimpleTodoApp/Entities/TodoItem.cs
namespace SimpleTodoApp.Entities;

public class TodoItem : Entity
{
    public string Description { get; set; } = string.Empty;
}

SimpleTodoApp/Entities/User.cs
namespace SimpleTodoApp.Entities;

public class User : Entity
{
    public string Name { get; set; } = string.Empty;
    public string Password { get; set; } = string.Empty;
}

SimpleTodoApp/Pages/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SimpleTodoApp.DAL;
using System.Security.Claims;

namespace SimpleTodoApp.Pages
{
    public class EditModel : PageModel
    {
        private readonly TodoDbContext dbContext;

        public EditModel(TodoDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        public TodoItem EditTodo { get; private set; } = default!;

        public async Task OnGetAsync(int id)
        {
            EditTodo = await dbContext.Todos.FirstAsync(i => i.Id == id);
        }

        public async Task<IActionResult> OnPostAsync(TodoItem todo)
        {
            todo.UserId = int.Parse(User.FindFirstValue("userId")!);
            if (string.IsNullOrEmpty(todo.Description))
            {
                ModelState.Clear();
                ModelState.AddModelError(nameof(todo.Description), "Description is required");
                return RedirectToPage(new { id = todo.Id });
            }

            dbContext.Update(todo);
            await dbContext.SaveChangesAsync();
            return RedirectToPage("Index");
        }
    }
}

SimpleTodoApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace SimpleTodoApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

SimpleTodoApp/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SimpleTodoApp.DAL;
using System.Security.Claims;

namespace SimpleTodoApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly TodoDbContext dbContext;

        public IndexModel(TodoDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        [BindProperty]
        public User UserModel { get; set; } = new();

        [BindProperty]
        public ICollection<TodoItem> Todos { get; private set; } = Array.Empty<TodoItem>();

        public async Task OnGetAsync()
        {
            var userId = GetUserId();
            Todos = await dbContext.Todos.Where(i => i.UserId == userId).ToListAsync();
            UserModel = await dbContext.Users.FirstAsync(i => i.Id == userId);
        }

        public async Task<IActionResult> OnPostEditMailAsync(User user)
        {
            var userId = GetUserId();
            var userEntity = await dbContext.Users.FirstAsync(i => i.Id == userId);
            userEntity.Email = user.Email;
            dbContext.Update(userEntity);
            await dbContext.SaveChangesAsync();
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostAsync(TodoItem todo)
        {
            if (string.IsNullOrEmpty(todo.Description))
            {
                ModelState.Clear();
                ModelState.AddModelError(nameof(todo.Description), "Description is required");
                return RedirectToPage();
            }
            todo.UserId = GetUserId();
            await dbContext.Todos.AddAsync(todo);
            await dbContext.SaveChangesAsync();
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostRemoveAsync(int id)
        {
            var toRemove = await dbContext.Todos.Where(i => i.Id == id).ToListAsync();
            foreach (var item in toRemove)
            {
                dbContext.Remove(item);
            }
            await dbContext.SaveChangesAsync();
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostEditAsync(int id)
        {
            if (!await dbContext.Todos.AnyAsync(i => i.Id == id))
            {
                return RedirectToPage();
            }
            return RedirectToPage("Edit", new { id = id });
        }

        private int GetUserId() => int.Parse(User.FindFirstValue("userId")!);
    }
}

SimpleTodoApp/Pages/Login.cshtml.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SimpleTodoApp.DAL;
using System.Security.Claims;

namespace SimpleTodoApp.Pages
{
    public class LoginModel : PageModel
    {
        private readonly TodoDbContext dbContext;

        public LoginModel(TodoDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        public async Task<IActionResult> OnPostAsync(User user)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToPage();
            }

            var existingUser = await dbContext.Users.FirstOrDefaultAsync(i => i.Name == user.Name);
            if (existingUser is not null)
            {
                if (BCrypt.Net.BCrypt.Verify(user.Password, existingUser.Password))
                {
                    await SignInAsync(existingUser.Id, existingUser.Name);
                    return RedirectToPage("/Index");
                }
                ModelState.AddModelError(nameof(user.Name), "Wrong password");
                return Page();
            }

            var userEntity = await dbContext.Users.AddAsync(new User
            {
                Name = user.Name,
                Password = BCrypt.Net.BCrypt.HashPassword(user.Password)
            });
            await dbContext.SaveChangesAsync();
            await SignInAsync(userEntity.Entity.Id, userEntity.Entity.Name);
            return RedirectToPage("/Index");
        }

        private async Task SignInAsync(int id, string name)
        {
            await HttpContext.SignInAsync("default", new ClaimsPrincipal(
                new ClaimsIdentity(new[]
                {
                    new Claim("userId", id.ToString()),
                    new Claim(ClaimTypes.Name, name),
                }, "default")),
                new AuthenticationProperties
                {
                    IsPersistent = false,
                });
        }
    }
}

SimpleTodoApp/Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SimpleTodoApp.Pages
{
    public class LogoutModel : PageModel
    {
        public async Task<IActionResult> OnGetAsync()
        {
            await HttpContext.SignOutAsync("default");
            return RedirectToPage("/Login");
        }
    }
}

SimpleTodoApp/Pages/Edit.cshtml
@page
@model EditModel
@{
    ViewData["Title"] = "Edit todo";
}

<h4>Edit a todo : @Model.EditTodo.Description</h4>
<form asp-page="Edit" method="post" class="form-inline">
    <input type="hidden" name="Id" value="@Model.EditTodo.Id" />
    <input type="text" id="Description" name="Description" class="form-control mb-1" placeholder="Description" />
    <input type="date" id="Deadline" name="Deadline" class="form-control" placeholder="Deadline" value="2023-06-01" />
    <div asp-validation-summary="All"></div>
    <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-save"></span> Update</button>
</form>

SimpleTodoApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<h2>Send notifications about deadlines to this email</h2>
<form method="post" asp-page="Index" asp-page-handler="EditMail" style="display: inline">
    <input type="email" id="Email" value="@Model.UserModel.Email" name="Email" class="form-control mb-2" placeholder="Email" />
    <button type="submit" style="margin-bottom: 20px" class="btn btn-primary"><span class="bi bi-plus-circle"></span> Save</button>
</form>
<br />

<h1>Todo List</h1>
<h4>Add a todo</h4>
<form asp-page="Index" method="post" class="form-inline">
    <input type="text" id="Description" name="Description" class="form-control mb-1" placeholder="Description" />
    <input type="date" id="Deadline" name="Deadline" class="form-control" placeholder="Deadline" value="2023-06-01" />
    <div asp-validation-summary="All"></div>
    <button type="submit" style="margin-bottom: 20px" class="btn btn-primary"><span class="bi bi-plus-circle"></span> Add</button>
</form>
<h4>Current Todo's</h4>

@if (!Model.Todos.Any())
{
    <p class="empty">The list is empty</p>
}
else
{
    <ul class="list-unstyled">
        @foreach (var todo in Model.Todos)
        {
            <li>
                <div class="container">
                    <div class="row">
                        <div class="col-sm-4">
                            <form method="post" asp-page="Index" asp-page-handler="Remove" style="display: inline">
                                <input type="hidden" name="Id" value="@todo.Id" />
                                <button type="submit" class="btn btn-link"><span class="bi bi-trash"></span></button>
                            </form>
                            <form method="post" asp-page="Index" asp-page-handler="Edit" style="display: inline">
                                <input type="hidden" name="Id" value="@todo.Id" />
                                <button type="submit" class="btn btn-link"><span class="bi bi-pencil"></span></button>
                            </form>
                            @todo.Description
                        </div>
                        <div class="col">
                            <strong>@todo.Deadline</strong>
                        </div>
                    </div>
                </div>
            </li>
        }
    </ul>
}
<style>
    .validation-summary-errors ul {
        list-style-type: none;
        color: red;
        padding: 0;
        margin: 0;
    }

    .empty {
        color: lightgray;
    }
</style>

SimpleTodoApp/Pages/Login.cshtml
@page
@model LoginModel
@{
    ViewData["Title"] = "Login";
}
<h1>@ViewData["Title"]</h1>
<br />

<form asp-page="Login" method="post" class="form-inline">
    <input type="text" id="Name" name="Name" class="form-control" placeholder="Name" />
    <input style="margin-top: 5px" min="0" type="password" id="Password" name="Password" class="form-control" placeholder="Password" />
    <br />
    <div asp-validation-summary="All" style="color:red"></div>
    <button type="submit" class="btn btn-primary">Login</button>
</form>

<br/>
<p>
    Test user name: 'Tom' Password: '123'   
    <br>
    This view is for login and also for registering new user. If original/unique name is provided, new user is created.
</p>

SimpleTodoApp/Pages/Logout.cshtml
@page
@model LogoutModel
@{
    ViewData["Title"] = "Logout";
}
<h1>@ViewData["Title"]</h1>

SimpleTodoApp/Pages/Shared/_Layout.cshtml
@using System.Security.Claims
@using Microsoft.AspNetCore.Http

@inject IHttpContextAccessor httpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SimpleTodoApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SimpleTodoApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">SimpleTodoApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        @if (httpContextAccessor.HttpContext?.User.Identity is not null && httpContextAccessor.HttpContext.User.Identity.IsAuthenticated)
                        {
                            <li>
                                <span class="nav-link text-dark"><b>Hello, @httpContextAccessor.HttpContext.User.FindFirstValue(ClaimTypes.Name)!</b></span>
                            </li>
                            <li>
                                <a class="nav-link text-dark" asp-area="" asp-page="/Logout">Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>